service: cryptocredentials-backend-v1

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table names here so we can use it while testing locally
  tableName: ${self:custom.stage}-profiles

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev 
  region: us-east-2

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}
    tableName: ${self:custom.tableName}

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ ProfilesTable, Arn ]
        - "Fn::GetAtt": [ LeadsTable, Arn ]

functions:
# Profiles
  createProfile:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /profiles
    # - method: POST request
    # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
    #     domain api call
    # - authorizer: authenticate using the AWS IAM role
    handler: create.main
    events:
      - http:
          path: profiles 
          method: post
          cors: true
          authorizer: aws_iam
  getProfile:
    handler: get.main
    events:
      - http:
          path: profiles/{id}
          method: get
          cors: true
          authorizer: aws_iam
  listProfiles:
    handler: list.main
    events:
      - http:
          path: profiles 
          method: get
          cors: true
          authorizer: aws_iam
  updateProfile:
    handler: update.main
    events:
      - http:
          path: profiles/{id}
          method: put
          cors: true
          authorizer: aws_iam
  deleteProfile:
    handler: delete.main
    events:
      - http:
          path: profiles/{id}
          method: delete
          cors: true
          authorizer: aws_iam
# Billing
  billing:
    # Defines an HTTP API endpoint that calls the main function in billing.js
    # - path: url path is /billing
    # - method: POST request
    handler: billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
# Create our resources with seperate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
